import "./globals.css";

import { Josefin_Sans } from "next/font/google";

import Providers from "./providers";

const josefinSans = Josefin_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${josefinSans.className} dark:bg-gray-900 dark:text-gray-50`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
